name       : dcd
version    : 0.13.6
release    : 1
source     :
    - git|https://github.com/dlang-community/DCD.git : v0.13.6
license    : MIT
component  : programming.tools
summary    : The D Completion Daemon is an auto-complete program for the D programming language
description: |
    DCD is not an IDE. DCD is designed to provide autocompletion for your favorite text editor. DCD consists of a client and a server. The client (dcd-client) is almost always used through a text editor script or plugin, though it can be used from the command line. The server (dcd-server) is responsible for caching imported files, calculating autocomplete information, and sending it back to the client.
builddeps  :
    - dmd
build      : |
    # Packager's note, seems to be bork with ldc
    %make
install    : |
    install -Dm00755 $workdir/bin/dcd-server $installdir/usr/bin/dcd-server
    install -Dm00755 $workdir/bin/dcd-client $installdir/usr/bin/dcd-client
