name       : dcd
version    : 0.15.2
release    : 2
source     :
    - git|https://github.com/dlang-community/DCD.git : c336004ed8c829840acc736918542242971cc4ba
license    : MIT
component  : programming.tools
summary    : The D Completion Daemon is an auto-complete program for the D programming language
description: |
    DCD is not an IDE. DCD is designed to provide autocompletion for your favorite text editor. DCD consists of a client and a server. The client (dcd-client) is almost always used through a text editor script or plugin, though it can be used from the command line. The server (dcd-server) is responsible for caching imported files, calculating autocomplete information, and sending it back to the client.
builddeps  :
    - ldc-devel
build      : |
    %make ldc
install    : |
    install -Dm00755 $workdir/bin/dcd-server $installdir/usr/bin/dcd-server
    install -Dm00755 $workdir/bin/dcd-client $installdir/usr/bin/dcd-client
    install -Dm00644 $workdir/bash-completion/completions/dcd-server $installdir/usr/share/bash-completion/completions/dcd-server
    install -Dm00644 $workdir/bash-completion/completions/dcd-client $installdir/usr/share/bash-completion/completions/dcd-client
    install -Dm00644 $workdir/man1/dcd-client.1 $installdir/usr/share/man/man1/dcd-client.1
    install -Dm00644 $workdir/man1/dcd-server.1 $installdir/usr/share/man/man1/dcd-server.1
